services:
  plantasia-admin:
    image: ghcr.io/annisa-rachma/plantasia-admin:latest
    container_name: plantasia-admin
    networks:
      - traefik_network
    labels:
      - "traefik.enable=true"

      # HTTPS router (websecure)
      - "traefik.http.routers.plantasia-admin.rule=Host(`plantasia-admin.annisarachma.com`)"
      - "traefik.http.routers.plantasia-admin.entrypoints=websecure"
      - "traefik.http.routers.plantasia-admin.tls.certresolver=letsencrypt"

      # Optional: HTTP router that redirects to HTTPS
      - "traefik.http.routers.plantasia-admin-http.rule=Host(`plantasia-admin.annisarachma.com`)"
      - "traefik.http.routers.plantasia-admin-http.entrypoints=web"
      - "traefik.http.routers.plantasia-admin-http.middlewares=redirect-to-https"

      # Define the service port (inside the container)
      - "traefik.http.services.plantasia-admin.loadbalancer.server.port=80"

      # Redirect HTTP to HTTPS
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

networks:
  traefik_network:
    external: true
